feature/OC-390
x-feed/x-feed-sdk-golang pull request #1
Opened 2018-08-16 10:09 UTC by taaraora

2018-08-17 13:41 UTC, cheshir commented on model.go
> +		fallthrough
Подход рабочий, применимый. Но в данном случае можно дважды задать явно. Позволит избежать ошибки по невнимательности в дальнейшем.

2018-08-17 13:41 UTC, cheshir commented on README.md
> +
Стоит описать какие зависимости нужны и как пользоваться. Например, добавить упоминание необходимости иметь докер для генерации протофайлов. Так же можно добавить ссылки на технологии которые используются (gRPC).

2018-08-17 13:41 UTC, cheshir commented on client.go
> +package xa
package `xa` – не самое описательное название для пакета. Как насчет заменить на что-то типа `xadapter`, `xfeed`?

2018-08-17 13:53 UTC, taaraora commented on client.go
> +package xa
Yep, ```xfeed``` is really self-explanatory, I'' change it in this PR.

2018-08-17 14:03 UTC, taaraora commented on README.md
> +
I agree with this, It is planned to be done when working prototype will be finished.
I think we can split this to next tasks:
0. Readme
1. Development\Contribution guide
2. Documentation\User guide

2018-08-18 20:24 UTC, cheshir commented on README.md
> +
Great idea.

2018-08-21 10:09 UTC, sdzyba requested changes

2018-08-21 10:09 UTC, sdzyba commented on client.go
> +func (c *Client) GetSession() *Session {
just `Session()`

2018-08-21 10:09 UTC, sdzyba commented on client.go
> +	client.conn, err = grpc.DialContext(client.ctx, cfg.ServerURI, opts...)
I'd prefer to have connection opening extracted to a separated method rather than having it in constructor.
Constructor conceptually is supposed to just initialize a struct, I believe.
As a user I may want to initialize all the components (besides `xfeed` client as well) first, validate the configuration and all, and only after that I would like to start everything I prepared. Current solution narrows my possibilities in such case.

2018-08-21 10:09 UTC, sdzyba commented on session.go
> +func (s *Session) EventsFeed(clientName string) (chan *EventEnvelope, chan *MarketEnvelope, error) {
Is there any specific reason `clientName` should be passed here while all other options are passed during the `client` initialization phase?

2018-08-21 10:09 UTC, sdzyba commented on session.go
> +	s.eventsFeedMutex.Unlock()
defer

2018-08-21 10:09 UTC, sdzyba commented on session.go
> +	s.eventSettlementsMutex.Unlock()
defer

2018-08-21 10:09 UTC, sdzyba commented on pkg/feed/events_stream.proto
> +        unknown = 0;
caps

2018-08-21 10:09 UTC, sdzyba commented on pkg/feed/events_stream.proto
> +        unknown = 0;
caps

2018-08-21 10:09 UTC, sdzyba commented on pkg/feed/events_stream.proto
> +        unknown = 0;
caps

2018-08-21 10:09 UTC, sdzyba commented on client.go
> +	Lg logger.LogEntry
why `Lg` and `Cfg` are public?

2018-08-21 10:09 UTC, sdzyba commented on config.go
> +
I think we can set defaults for most of the options here since user may not be interested in diving deeply into the configuration. Although some of them like `ClientID` and `ServerURI`, for sure, should be required with corresponding errors in case they're missing.

2018-08-21 10:09 UTC, sdzyba commented on config.go
> +type Config struct {
should `Config` be a public struct?

2018-08-21 10:09 UTC, sdzyba commented on session.go
> +type Session struct {
What do you think if user would only have to initialize a `Client`, start it and call methods only on `Client` to get event, entities, etc channels? I mean, tiny and simple SDK's API (with possibility to override defaults, of course) would definitely make user happier. `Session` can be a private struct in that case.

2018-08-21 10:09 UTC, sdzyba commented on model.go
> +func NewFeedAction(action pb.DiffType) FeedAction {
Should this and all the constructors above in `model.go` be public?

2018-08-21 10:41 UTC, taaraora commented on client.go
> +func (c *Client) GetSession() *Session {
Yep, thx.

2018-08-21 10:42 UTC, taaraora commented on session.go
> +func (s *Session) EventsFeed(clientName string) (chan *EventEnvelope, chan *MarketEnvelope, error) {
Makes sense, I'll remove it.

2018-08-21 10:42 UTC, taaraora commented on session.go
> +	s.eventsFeedMutex.Unlock()
wow, nice catch, thx!

2018-08-21 10:43 UTC, taaraora commented on session.go
> +	s.eventSettlementsMutex.Unlock()
thx!

2018-08-21 10:43 UTC, taaraora commented on client.go
> +	Lg logger.LogEntry
I'm agree, there is no point to do that.

2018-08-21 10:44 UTC, taaraora commented on config.go
> +
Yep, config defaults and validation will be addressed in future PRs.

2018-08-21 10:45 UTC, taaraora commented on config.go
> +type Config struct {
Yes, to enable user create instance of it and pass to client creation function.

2018-08-21 10:52 UTC, taaraora commented on client.go
> +	client.conn, err = grpc.DialContext(client.ctx, cfg.ServerURI, opts...)
I like approach when NewClient() creates fully configured and already ready for work client instance.

2018-08-21 10:55 UTC, taaraora commented on session.go
> +type Session struct {
I agree with you, that it is better to merge current functionality to single Client with a few methods.
But I've separated client and session to simplify adding new functionality in next PR.

2018-08-21 10:58 UTC, taaraora commented on model.go
> +func NewFeedAction(action pb.DiffType) FeedAction {
Nice catch. fixed.

2018-08-21 11:05 UTC, taaraora commented on model.go
> +		fallthrough
I like approach with ```fallthrough``` It looks more readable.

2018-08-21 12:12 UTC, cheshir commented on client.go
> +	Lg logger.LogEntry
‘Lg’ is not the known shortening. I propose to use ‘Logger’. It will not shadow package name.

2018-08-21 12:12 UTC, cheshir commented on client.go
> +	client.conn, err = grpc.DialContext(client.ctx, cfg.ServerURI, opts...)
There is another one option when `New` returns ready-to-use service.
As a user I want to have API as simple as possible.

2018-08-21 12:12 UTC, cheshir commented on session.go
> +	entitiesMutex sync.Mutex
I can't figure out what data protect these mutexes.

2018-08-21 12:12 UTC, cheshir commented on session.go
> +
Unnecessary new line.

2018-08-21 12:12 UTC, cheshir commented on session.go
> +	entitiesMutex sync.Mutex
I think it would be great to describe purposes of these mutexes.

2018-08-21 12:12 UTC, cheshir commented on session.go
> +			}
Is this check really necessary? Can we omit it?

2018-08-21 12:12 UTC, cheshir commented on session.go
> +	eventsStream    chan *EventEnvelope
Did you think about single channel with changes for all entities?

2018-08-21 12:22 UTC, taaraora commented on pkg/feed/events_stream.proto
> +        unknown = 0;
These proto files are imported from non public yet x-feed repo, I prefer to do not modify them.

2018-08-21 12:22 UTC, taaraora commented on pkg/feed/events_stream.proto
> +        unknown = 0;
These proto files are imported from non public yet x-feed repo, I prefer to do not modify them.

2018-08-21 12:22 UTC, taaraora commented on pkg/feed/events_stream.proto
> +        unknown = 0;
These proto files are imported from non public yet x-feed repo, I prefer to do not modify them.

2018-08-21 12:28 UTC, taaraora commented on session.go
> +	entitiesMutex sync.Mutex
Each of those mutexes prevent concurrent invocation of specific API method.
Because there is no guarantee to predict behavior of x-feed when multiple clients with the same clientName is connected.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +	SportDescription struct {
This is a minor detail, but I think this style of declaration negatively affects readability. I opened this file and immediately I had to readjust to different style, normally I would expect several types to be defined in succession, not only single "type" declaration followed by a lengthy list of types to be declared. But this might be just me.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +		SportID     int32
`ID` `Name` would be better, same goes for all other instances of using a EntityNamePrefix.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +	State struct {
PointState? I don't know enough to figure out a better name for this.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +		MarketType   int32
This might be a problem, I think it would be better to either define a universal ID or specific MarketTypeID/EventID etc if you envision them being different in the future.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +		MarketID     string
Is this intended to be a string? A universal ID type would be better imo e.g. `type ID string`. Same goes for all other instances of this.

2018-08-21 12:29 UTC, ivanthescientist commented on model.go
> +		fallthrough
I think it just draws attention unnecessarily, removing this case altogether (since in this particular case its handled by `default`) would be much better option than to keep it here imo.

2018-08-21 12:29 UTC, ivanthescientist commented on pkg/logger/logger.go
>  type LogEntry interface {
This name looks a bit misleading to be honest, Entry should be a name for some singular entity, which at the maximum contain a set of fields that are necessary to append it to actual log file or log stream of sorts.

Long story short, I would rename the package into log or logging and this interface into Logger, because that would be an accurate description of what it actually does - logs stuff.

2018-08-21 12:29 UTC, ivanthescientist commented on session.go
> +func (s *Session) SettlementsFeed(lastConsumed time.Time) (chan *EventSettlementEnvelope, error) {
As a side note, all methods here are incredibly long, would it be possible to split them into set of smaller specialized functions? For example all those background goroutines you launch can probably become separate private methods.

2018-08-21 12:29 UTC, ivanthescientist commented on session.go
> +	err = s.limiter.Wait(context.Background())
Here's a wild thought: how about a context as argument and using it instead of background? Not sure if this will be necessary, but overall having that option on API level is better imo - maybe I as client want to do something else between my requests.

2018-08-21 12:31 UTC, taaraora commented on session.go
> +
This new line respects our internal style-guide.

2018-08-21 12:33 UTC, taaraora commented on session.go
> +			}
I think it's better to do a check than get unhandled panic.

2018-08-21 12:33 UTC, ivanthescientist commented on session.go
> +	eventsStream    chan *EventEnvelope
I would personally want to have separate Market and Event update streams simply because markets have to be processed much faster than event changes and I'd have to demultiplex them myself anyways if there were in same stream.

2018-08-21 12:36 UTC, taaraora commented on session.go
> +	eventsStream    chan *EventEnvelope
Yes, but for me as for end user of this API is more convenient ho have strongly typed separate channels. Anyway I need to have strongly typed entities, also there are totally different handlers are used for each of them.

2018-08-21 12:49 UTC, sdzyba commented
Approved 👍

2018-08-21 12:51 UTC, sdzyba approved these changes

2018-08-21 12:52 UTC, taaraora commented on session.go
> +	err = s.limiter.Wait(context.Background())
This is shared limiter to decrease number of concurrent requests to the x-feed API. There is no more intentions.  I think it not necessary.

2018-08-21 12:53 UTC, taaraora commented on pkg/logger/logger.go
>  type LogEntry interface {
The idea is sound.

2018-08-21 13:00 UTC, taaraora commented on model.go
> +		SportID     int32
Oh, I really need to remove unnecessary duplication.

2018-08-21 13:10 UTC, taaraora commented on model.go
> +	State struct {
It contains counter of different kinds of resulting for game: goals, points, Red cards, yellow cards, corners, etc...

2018-08-21 13:10 UTC, taaraora commented on model.go
> +	SportDescription struct {
Such approach groups tightly related to each other entities.

2018-08-21 14:32 UTC, cheshir approved these changes

2018-08-21 14:32 UTC, merged